name: 'Terraform Destroy Infrastructure'

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm infrastructure destruction'
        required: true
        type: string
        pattern: '^DESTROY$'
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development

env:
  TF_VERSION: '1.5.0'
  AWS_REGION: 'us-east-1'

permissions:
  contents: read
  id-token: write

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Validate Destroy Confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "❌ Destroy confirmation failed. Must type 'DESTROY' to proceed."
          exit 1
        fi
        echo "✅ Destroy confirmed for environment: ${{ github.event.inputs.environment }}"
        
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Plan Destroy
      id: plan-destroy
      run: terraform plan -destroy -no-color -out=destroy-plan
      
    - name: Show Destroy Plan
      run: terraform show destroy-plan
      
    - name: Terraform Destroy
      run: terraform apply destroy-plan
      
    - name: Comment Destroy Result
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const output = `#### 🗑️ Terraform Destroy Completed
            
            **Environment:** ${{ github.event.inputs.environment }}
            **Action:** Infrastructure has been successfully destroyed
            
            **⚠️ Warning:** All resources have been removed. This action cannot be undone.
            
            *Destroyed by @${{ github.actor }}*`;
            
            // Try to create a commit comment
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: output
            });
          } catch (error) {
            console.log('Could not create commit comment:', error.message);
          }
